### 지정맥 영상용 data augmentation

Keras의 ImageDataGenerator클래스를 사용하여 data augmentation하는 코드이다.

ImageDataGenerator클래스는 생성 시 인자로 다양한 변수를 받는데 그 중에 brightness_range=[a,b]는 밝기 기준 augmentation 수행 코드이다.

a가 0.5이면 이미지는 최소 0.5배 밝기가 낮아지고 b가 1.5면 이미지는 최대 1.5배 밝기가 높아진다.

ImageDataGenerator클래스는 [a,b] 사이의 값을 랜덤하게 뽑아 augmentation한다. 

밝기 기준으로 augmentation하는 코드는 바로 아래 Cell에 있다.

In [13]:
import os
import numpy as np
import cv2
from keras.preprocessing.image import ImageDataGenerator, img_to_array
from PIL import Image
from skimage import exposure
import glob
import platform


# Brightness_IMG_SAVE_PATH에는 밝기기준 augmentation 결과가 저장됨
Brightness_IMG_SAVE_PATH = "C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/Brightness_result"
# Contrast_IMG_SAVE_PATH에는 대비기준 augmentation 결과가 저장됨
Contrast_IMG_SAVE_PATH = "C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/Contrast_result"
# Mixture_IMG_SAVE_PATH에는 밝기와 대비가 모두 augmentation에 저장됨
Mixture_IMG_SAVE_PATH = "C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/Mixture_result"
train_path="C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/raw_per person"

if not os.path.exists(Brightness_IMG_SAVE_PATH):
    os.mkdir(Brightness_IMG_SAVE_PATH)
if not os.path.exists(Contrast_IMG_SAVE_PATH):
    os.mkdir(Contrast_IMG_SAVE_PATH)
if not os.path.exists(Mixture_IMG_SAVE_PATH):
    os.mkdir(Mixture_IMG_SAVE_PATH)
    
# data augmentation을 담당하는 ImageDataGenerator 클래스 아래 코드는 밝기값 도메인에서의 data_augmentation을 진행
# brightness_range=[a,b]에서 a가 0.5이면 이미지는 최소 0.5배 밝기가 낮아지고 b가 1.5면 이미지는 최대 1.5배 밝기가 높아진다.

# opencv 라이브러리를 통해 이미지 읽어오는 코드
# cv_img = [cv2.imread(file) for file in glob.glob("./정맥전체/*.bmp")]
# for f in os.listdir(train_path):
#     files =(train_path+'/'+f)
#     img=cv2.imread(r"C:\Users\jmlee\Desktop\4학년 1학기\졸프\U-Net\정맥전체/*.bmp",cv2.IMREAD_COLOR)

#한글이름 사진 로드
def hangulFilePathImageRead (filePath ) :

    stream = open( filePath.encode("utf-8") , "rb")
    bytes = bytearray(stream.read())
    numpyArray = np.asarray(bytes, dtype=np.uint8)

    return cv2.imdecode(numpyArray , cv2.IMREAD_COLOR)  #3채널로 가져오기



if __name__ == '__main__':
    # OS Platform 정보
    print(platform.platform())
    for f in os.listdir(train_path):  
        if f.split('.')[1] =='jpg':
            filePath = (r"C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/raw_per person"+'/'+f)  
            cv_img = hangulFilePathImageRead(filePath)
            cv_img = cv2.cvtColor(cv_img,cv2.COLOR_BGR2RGB)
            pil_img = Image.fromarray(cv_img)
            # ImageDataGenerator 클래스의 경우 파이썬 이미지 라이브러리인 PIL 이미지 입력을 기준으로함으로 opencv 이미지에서 PIL이미지로 변환하여야한다.
            # pil_img를 ImageDataGenerator클래스의 flow함수 입력으로 넣기 위해 PIL img 를 array로 바꾼후 랭크가 4인 형태로 변환
            # ImageDataGenerator 클래스의 함수들은 기본적으로 mini_batch를 지원하기 때문에 랭크가 4인 형태이다. 
            #example : np.shape 가 ( none, image.rows, image.cols, image.depth) 이다.
            input_img = img_to_array(pil_img) # np.shape(150, 60, 1)
            input_img = input_img[None] # np.shape(1, 150, 60, 1)
#             bright()
            Contrast()
#             Mixture()
            

Windows-10-10.0.18362-SP0


In [3]:
print(type(cv_img))

<class 'numpy.ndarray'>


In [4]:
print(cv_img.shape)

(60, 152, 3)


In [5]:
print(input_img)

[[[[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 12.  12.  12.]
   [196. 196. 196.]
   [204. 204. 204.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 27.  27.  27.]
   [205. 205. 205.]
   [210. 210. 210.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [ 33.  33.  33.]
   [205. 205. 205.]
   [206. 206. 206.]]

  ...

  [[125. 125. 125.]
   [122. 122. 122.]
   [130. 130. 130.]
   ...
   [209. 209. 209.]
   [209. 209. 209.]
   [192. 192. 192.]]

  [[116. 116. 116.]
   [113. 113. 113.]
   [122. 122. 122.]
   ...
   [187. 187. 187.]
   [222. 222. 222.]
   [210. 210. 210.]]

  [[ 54.  54.  54.]
   [ 51.  51.  51.]
   [ 61.  61.  61.]
   ...
   [103. 103. 103.]
   [183. 183. 183.]
   [191. 191. 191.]]]]


In [8]:
# 아래는 랜덤하게 생성된 이미지를 20개 생성하고 Brightness_IMG_SAVE_PATH에 저장하는 코드
# the .flow() command below generates batches of randomly transformed images 
# and saves the results to the IMG_SAVE_PATH directory
b_datagen = ImageDataGenerator(brightness_range=[0.5,1.5], width_shift_range=0.05, height_shift_range=0.05)
def bright():
    i = 0
    #'C:/Users/jmlee/Desktop/4학년 1학기/졸프/U-Net/정맥전체/[SEG]홍성용_9_9.bmp'
    for batch in b_datagen.flow(input_img, batch_size=1, save_to_dir=Brightness_IMG_SAVE_PATH, save_prefix=f.split('.jpg')[0], save_format='jpg'):
        i += 1
        if i > 20:
            break  # otherwise the generator would loop indefinitely

# contrast를 변형하는 data augmentation

contrast를 변형하는 augmentation은 ImageDataGenerator가 기본 인수로 제공하지 않기 때문에 따로 contrast를 변형하는 함수를 만들어야한다.

ImageDataGenerator클래스 생성 시에 사용된 함수는 get_random_contrast_stretch()로 랜덤 정수를 생성해 이미지의 contrast를 랜덤하게 stretch시킨다.

In [11]:
# contrast_stretch을 수행하는 함수
def get_random_contrast_stretch():
    
    def random_contrast_stretch(input_img):
        # Contrast stretching by random int
        img_rescale = exposure.rescale_intensity(input_img, in_range=tuple([np.random.randint(0,100), np.random.randint(155,255)]))
        return img_rescale

    return random_contrast_stretch


c_datagen = ImageDataGenerator(width_shift_range=0.05, height_shift_range=0.05, preprocessing_function=get_random_contrast_stretch())


In [12]:
# ImageDataGenerator의 flow함수를 사용하면 랜덤하게 변형된 이미지가 생성된다. 
# 아래는 랜덤하게 생성된 이미지를 20개 생성하고 저장하는 코드
def Contrast():
    i = 0
    for batch in c_datagen.flow(input_img, batch_size=1, save_to_dir=Contrast_IMG_SAVE_PATH, save_prefix=f.split('.jpg')[0], save_format='jpg'):
        i += 1
        if i > 20:
            break  # otherwise the generator would loop indefinitely

# Brightness와 contrast를 모두 사용한 data augmentation

ImageDataGenerator에 'brightness_range'와 'preprocessing_function=get_random_contrast_stretch()'을 설정하게 되면 

contrast와 밝기를 동시에 사용하여 data augmentation을 수행할 수 있다.

In [ ]:
def Mixture():
    m_datagen = ImageDataGenerator(brightness_range=[0.8,1.2], width_shift_range=0.05, height_shift_range=0.05, preprocessing_function=get_random_contrast_stretch())

    i = 0
    for batch in m_datagen.flow(input_img, batch_size=1, save_to_dir=Mixture_IMG_SAVE_PATH, save_prefix=f.split('.jpg')[0], save_format='jpg'):
        i += 1
        if i > 20:
            break  # otherwise the generator would loop indefinitely